mail_num = 1
wait_edit = 1000
wait_before_send = 10000
wait_after_send = 12000

[sent_mail]
x = 400
y = 200

[add_attach.button]
x = 240
y = 40

[add_attach.file_list]
x = 530
y = 140

[[mail]]

[mail.start_pos]
x = 2000
y = 600

[mail.edit_menu_pos]
x = 2060
y = 760

[mail.title_date_pos]
x = 610
y = 220

[mail.content_date_pos]
x = 860
y = 520

[mail.content_attach_pos]
x = 1030
y = 630

[mail.title_attach_pos]
x = 400
y = 260

[mail.final_pos]
x = 1050
y = 650

[[mail]]

[mail.start_pos]
x = 2000
y = 600

[mail.edit_menu_pos]
x = 2060
y = 760

[mail.title_date_pos]
x = 560
y = 220

[mail.content_date_pos]
x = 780
y = 520

[mail.content_attach_pos]
x = 1030
y = 630

[mail.title_attach_pos]
x = 400
y = 260

[mail.final_pos]
x = 1050
y = 650

[[mail]]

[mail.start_pos]
x = 2000
y = 600

[mail.edit_menu_pos]
x = 2060
y = 760

[mail.title_date_pos]
x = 450
y = 220

[mail.content_date_pos]
x = 640
y = 500

[mail.content_attach_pos]
x = 990
y = 520

[mail.title_attach_pos]
x = 400
y = 260

[mail.final_pos]
x = 1050
y = 650

[[mail]]

[mail.start_pos]
x = 2000
y = 600

[mail.edit_menu_pos]
x = 2060
y = 760

[mail.title_date_pos]
x = 470
y = 210

[mail.content_date_pos]
x = 655
y = 455

[mail.content_attach_pos]
x = 0
y = 0

[mail.title_attach_pos]
x = 0
y = 0

[mail.final_pos]
x = 1050
y = 650

[[mail]]

[mail.start_pos]
x = 2000
y = 600

[mail.edit_menu_pos]
x = 2060
y = 760

[mail.title_date_pos]
x = 470
y = 210

[mail.content_date_pos]
x = 655
y = 420

[mail.content_attach_pos]
x = 0
y = 0

[mail.title_attach_pos]
x = 0
y = 0

[mail.final_pos]
x = 1050
y = 650